apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ projectname }}-elasticsearch-pod
  name: {{ projectname }}-elasticsearch-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: es01
    image: {{ elasticsearch.image.name }}
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ elasticsearch.resources.requests.memory }}
      limits:
        memory: {{ elasticsearch.resources.limits.memory }}
    ports:
    - containerPort: {{ elasticsearch.port.requests.container }}
      hostPort: {{ elasticsearch.port.requests.host }}
      hostIP: {{ elasticsearch.port.requests.ip }}
      protocol: tcp
    - containerPort: {{ elasticsearch.port.node_communications.container }}
      hostPort: {{ elasticsearch.port.node_communications.host }}
      hostIP: {{ elasticsearch.port.node_communications.ip }}
      protocol: tcp
    env:
    - name: ES_JAVA_OPTS
      value: '{{ elasticsearch.java_opts }}'
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      name: elasticsearch-yml
      readOnly: true
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-data
  volumes:
  - name: elasticsearch-yml
    hostPath:
      path: /opt/elk/elasticsearch.yml
  - name: elasticsearch-data
    persistentVolumeClaim:
      claimName: {{ projectname }}-elasticsearch-data
