apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kibana-pod
  name: kibana-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: k01
    image: {{ kibana.image.name }}
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    resources:
      requests:
        memory: {{ kibana.resources.requests.memory }}
      limits:
        memory: {{ kibana.resources.limits.memory }}
    ports:
    - containerPort: {{ kibana.port.server.container }}
      hostPort: {{ kibana.port.server.host }}
      hostIP: {{ kibana.port.server.ip }}
      protocol: tcp
    volumeMounts:
    - mountPath: /usr/share/kibana/config/kibana.yml
      name: kibana-yml
  volumes:
  - name: kibana-yml
    hostPath:
      path: /opt/elk/kibana.yml
