apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ projectname }}-logstash-pod
  name: {{ projectname }}-logstash-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: ls01
    image: {{ logstash.image.name }}
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ logstash.resources.requests.memory }}
      limits:
        memory: {{ logstash.resources.limits.memory }}
    ports:
    - containerPort: {{ logstash.port.webapi.container }}
      hostPort: {{ logstash.port.webapi.host }}
      hostIP: {{ logstash.port.webapi.ip }}
      protocol: tcp
    - containerPort: {{ logstash.port.beats.container }}
      hostPort: {{ logstash.port.beats.host }}
      hostIP: {{ logstash.port.beats.ip }}
      protocol: tcp
    volumeMounts:
    - mountPath: /usr/share/logstash/data
      name: logstash-data
    - mountPath: /usr/share/logstash/config/logstash.yml
      name: logstash-yml
      readOnly: true
    - mountPath: /usr/share/logstash/pipeline
      name: logstash-pipelines
      readOnly: true
    - mountPath: /usr/share/logstash/config/pipelines.yml
      name: logstash-pipelines-conf
      readOnly: true
  volumes:
  - name: logstash-data
    persistentVolumeClaim:
      claimName: {{ projectname }}-logstash-data
  - name: logstash-yml
    hostPath:
      path: /opt/elk/logstash.yml
  - name: logstash-pipelines
    hostPath:
      path: /opt/elk/pipelines
  - name: logstash-pipelines-conf
    hostPath:
      path: /opt/elk/pipelines.yml
